title: Kevin Behringer - Applicant for UWGB Manager of Web Operations
description: > I am thrilled to be considered as a candidate for the UW-Green Bay Manager of Web Operations. My affinity for the school and expertise in web design, development, and marketing make me uniquely suited for this position. # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Kevin Behringer # add your name
author-img: kevin-behringer.jpg # add your photo
about-author: I'm thrilled to be considered for the position of Manager of Web Operations at UW-Green Bay. These examples of some of my completed web design and development projects will help illustrate that I am well-suited for this position.
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: kevinbehringer@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
